ar_covid_latest_index: Sunday, Jan 17, 2021
counties:
- Union
- Ouachita
- Columbia
- Calhoun
- Bradley
- Ashley
generate_bullet: false
generate_line: false
generate_regional_map: false
generate_state_map: false
generate_xkcd_graph: false
group_uid: 515810702698017
level: DEBUG
logging: console
post_negative_results: false
post_to_facebook: false
primary_county: Union
send_email: false
test_group_uid: 1035931633567987
test_mode: true
urls:
  ar_covid: https://raw.githubusercontent.com/Arkansascovid/Main/master/master_file.csv
  county_geojson: https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json
  rt: https://d14wlfuexuxgcm.cloudfront.net/covid/rt.csv
who_threshold: 0.05
